import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  output: 'standalone',
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_GMAIL_SUPABASE_URL: process.env.NEXT_PUBLIC_GMAIL_SUPABASE_URL,
    NEXT_PUBLIC_GMAIL_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_GMAIL_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_GMAIL_AUTH_URL: process.env.NEXT_PUBLIC_GMAIL_AUTH_URL,
    NEXT_PUBLIC_DAILY_ROOM_URL: process.env.NEXT_PUBLIC_DAILY_ROOM_URL,
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_DATABASE_URL: process.env.NEXT_PUBLIC_DATABASE_URL,
    NEXT_PUBLIC_ASSISTANTS_BASEURL: process.env.NEXT_PUBLIC_ASSISTANTS_BASEURL,
    NEXT_PUBLIC_KB_SERVICE_BASEURL: process.env.NEXT_PUBLIC_KB_SERVICE_BASEURL,
    EXOTEL_API_URL: process.env.EXOTEL_API_URL,
    EXOTEL_API_KEY: process.env.EXOTEL_API_KEY,
    EXOTEL_FUNCTIONS_KEY: process.env.EXOTEL_FUNCTIONS_KEY,
    EXOTEL_ACCOUNT_SID: process.env.EXOTEL_ACCOUNT_SID,
    EXOTEL_BASE_URL: process.env.EXOTEL_BASE_URL,
    NEXT_PUBLIC_EXOTEL_CALLBACK_URL: process.env.NEXT_PUBLIC_EXOTEL_CALLBACK_URL
  },
  typescript: {
    ignoreBuildErrors: true,
  },

};

export default nextConfig;
